### PR TITLE
Update RF12_Demo_atmega328.ino

### PR DESCRIPTION
**Pull request by Bra1nK**
Increase transmit buffer sizes from 20 to 66 bytes for use by Emoncms PacketGen Modules

### CODE REVIEW

**Comment by glynhudson** [comment]
Great, thanks! Trystan was wondering why packetgen packets > 20 bytes were not getting through.

**Comment by Bra1nK** [comment]
I've submitted the compiled file as well, maybe the other versions of this should also be updated although I don't have the facility to test them (Full_RF12demo_atmega328,  RF12_Demo_atmega328_OLED and possibly Pre_compiled_ATtiny84_RF12_Demo_hex if it doesn't exceed the max size for the ATtiny84 with the bigger buffers)

**Comment by glynhudson** [comment]
I think we should let the maintains for the other examples update the hex
files @mctully has been updating the 'full' demo recently

On 10 April 2014 10:15, Bra1nK notifications@github.com wrote:

> I've submitted the compiled file as well, maybe the other versions of this
> should also be updated although I don't have the facility to test them
> (Full_RF12demo_atmega328, RF12_Demo_atmega328_OLED and possibly
> Pre_compiled_ATtiny84_RF12_Demo_hex if it doesn't exceed the max size for
> the ATtiny84 with the bigger buffers)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/mharizanov/RFM2Pi/pull/8#issuecomment-40057892
> .

## 

Glyn Hudson

Home: +44(0)1286479462
Mobile: +44(0)7769871550
Office: +44(0)1248672607

http://openenergymonitor.org
http://megni.co.uk
http://adventuresplusnorthwales.blogspot.com

**Comment by Bra1nK** [comment]
Excellent, suits me, I wouldn't want update something I couldn't fully test.

**Pull request merged**
